### ISSUE TITLE
[Question] About fonts

### ISSUE THREAD

**Issue by WhoAteDaCake** [skillbert/alt1#10]
Hello, was just looking through the code (amazing work you're doing) and I've noticed the fonts stored in the OCR library. Did you generate these fonts yourself, or are they official rs3 fonts? thanks :)

**Comment by skillbert** [comment]
The current method is to just use screenshots and use `@alt1/font-loader` to extract them from the background. Some of the older fonts are extracted from old cache dumps that someone sent me.

**Comment by WhoAteDaCake** [comment]
Thanks, great to know! Just experimenting with text extraction from rs3 screenshots, was wondering if there was an easier method.
